/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.sources.vistas;

/**
 *
 * @author keyor
 */
public class CopiaSimplex extends javax.swing.JPanel {

    /**
     * Creates new form CopiaSimplex
     */
    public CopiaSimplex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtObjetivo = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        TxtRes = new javax.swing.JTextField();
        BtnMenu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PanelTabla = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TxtRestric1 = new javax.swing.JTextField();
        TxtRestric2 = new javax.swing.JTextField();
        TxtRestric3 = new javax.swing.JTextField();
        TxtRestric4 = new javax.swing.JTextField();
        BtnGenerar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BtnLimpiar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 800));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("METODO SIMPLEX");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Z");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        TxtObjetivo.setBackground(new java.awt.Color(0, 0, 102));
        TxtObjetivo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TxtObjetivo.setForeground(new java.awt.Color(255, 255, 255));
        TxtObjetivo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        TxtObjetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtObjetivoActionPerformed(evt);
            }
        });
        jPanel1.add(TxtObjetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 280, 30));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 102));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minimización", "Maximización" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 116, -1, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Respuesta");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));

        TxtRes.setBackground(new java.awt.Color(0, 0, 102));
        TxtRes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TxtRes.setForeground(new java.awt.Color(255, 255, 255));
        TxtRes.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(TxtRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 108, 280, 30));

        BtnMenu.setBackground(new java.awt.Color(102, 102, 102));
        BtnMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Menu");
        BtnMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 8, -1, -1));

        jPanel1.add(BtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 110, 40));

        javax.swing.GroupLayout PanelTablaLayout = new javax.swing.GroupLayout(PanelTabla);
        PanelTabla.setLayout(PanelTablaLayout);
        PanelTablaLayout.setHorizontalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelTablaLayout.setVerticalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(PanelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 680, 490));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Restricciones");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        TxtRestric1.setBackground(new java.awt.Color(0, 0, 102));
        TxtRestric1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TxtRestric1.setForeground(new java.awt.Color(255, 255, 255));
        TxtRestric1.setAutoscrolls(false);
        TxtRestric1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(TxtRestric1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 250, 30));

        TxtRestric2.setBackground(new java.awt.Color(0, 0, 102));
        TxtRestric2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TxtRestric2.setForeground(new java.awt.Color(255, 255, 255));
        TxtRestric2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(TxtRestric2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 250, 30));

        TxtRestric3.setBackground(new java.awt.Color(0, 0, 102));
        TxtRestric3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TxtRestric3.setForeground(new java.awt.Color(255, 255, 255));
        TxtRestric3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(TxtRestric3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 250, 30));

        TxtRestric4.setBackground(new java.awt.Color(0, 0, 102));
        TxtRestric4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TxtRestric4.setForeground(new java.awt.Color(255, 255, 255));
        TxtRestric4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(TxtRestric4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 250, 30));

        BtnGenerar.setBackground(new java.awt.Color(102, 102, 102));
        BtnGenerar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnGenerar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Generar");
        BtnGenerar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 8, -1, -1));

        jPanel1.add(BtnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 200, 120, 40));

        BtnLimpiar.setBackground(new java.awt.Color(102, 102, 102));
        BtnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnLimpiar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Limpiar");
        BtnLimpiar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 8, -1, -1));

        jPanel1.add(BtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 270, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtObjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtObjetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtObjetivoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel BtnGenerar;
    public javax.swing.JPanel BtnLimpiar;
    public javax.swing.JPanel BtnMenu;
    public javax.swing.JPanel PanelTabla;
    public javax.swing.JTextField TxtObjetivo;
    public javax.swing.JTextField TxtRes;
    public javax.swing.JTextField TxtRestric1;
    public javax.swing.JTextField TxtRestric2;
    public javax.swing.JTextField TxtRestric3;
    public javax.swing.JTextField TxtRestric4;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
