/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.sources.vistas;

/**
 *
 * @author keyor
 */
public class VistaMetodoSimplex extends javax.swing.JPanel {

    /**
     * Creates new form VistaMetodoSimplex
     */
    public VistaMetodoSimplex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelTabla = new javax.swing.JPanel();
        BtnGenerar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnLimpiar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BtnRegresar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BtnMenu = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CmbOpciones = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        TxtRes1 = new javax.swing.JTextField();
        TxtRes2 = new javax.swing.JTextField();
        TxtRes3 = new javax.swing.JTextField();
        TxtRes4 = new javax.swing.JTextField();
        TxtZ = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtResultado = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setText("Metodo Simplex");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        javax.swing.GroupLayout PanelTablaLayout = new javax.swing.GroupLayout(PanelTabla);
        PanelTabla.setLayout(PanelTablaLayout);
        PanelTablaLayout.setHorizontalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        PanelTablaLayout.setVerticalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jPanel1.add(PanelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 460, 250));

        BtnGenerar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Generar");

        javax.swing.GroupLayout BtnGenerarLayout = new javax.swing.GroupLayout(BtnGenerar);
        BtnGenerar.setLayout(BtnGenerarLayout);
        BtnGenerarLayout.setHorizontalGroup(
            BtnGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnGenerarLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(31, 31, 31))
        );
        BtnGenerarLayout.setVerticalGroup(
            BtnGenerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnGenerarLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel1.add(BtnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, 30));

        BtnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Limpiar");

        javax.swing.GroupLayout BtnLimpiarLayout = new javax.swing.GroupLayout(BtnLimpiar);
        BtnLimpiar.setLayout(BtnLimpiarLayout);
        BtnLimpiarLayout.setHorizontalGroup(
            BtnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnLimpiarLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(32, 32, 32))
        );
        BtnLimpiarLayout.setVerticalGroup(
            BtnLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnLimpiarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(BtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 120, 30));

        BtnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Regresar");

        javax.swing.GroupLayout BtnRegresarLayout = new javax.swing.GroupLayout(BtnRegresar);
        BtnRegresar.setLayout(BtnRegresarLayout);
        BtnRegresarLayout.setHorizontalGroup(
            BtnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnRegresarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        BtnRegresarLayout.setVerticalGroup(
            BtnRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnRegresarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel1.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, 30));

        BtnMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Menu");

        javax.swing.GroupLayout BtnMenuLayout = new javax.swing.GroupLayout(BtnMenu);
        BtnMenu.setLayout(BtnMenuLayout);
        BtnMenuLayout.setHorizontalGroup(
            BtnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnMenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        BtnMenuLayout.setVerticalGroup(
            BtnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel1.add(BtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, 30));

        jLabel6.setText("Z");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 20, -1));

        CmbOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(CmbOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        jLabel7.setText("Restricciones");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        jPanel1.add(TxtRes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, -1));
        jPanel1.add(TxtRes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 120, -1));
        jPanel1.add(TxtRes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 120, -1));
        jPanel1.add(TxtRes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 120, -1));
        jPanel1.add(TxtZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 110, -1));

        jLabel8.setText("Resultado");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));
        jPanel1.add(TxtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel BtnGenerar;
    public javax.swing.JPanel BtnLimpiar;
    public javax.swing.JPanel BtnMenu;
    public javax.swing.JPanel BtnRegresar;
    public javax.swing.JComboBox<String> CmbOpciones;
    public javax.swing.JPanel PanelTabla;
    public javax.swing.JTextField TxtRes1;
    public javax.swing.JTextField TxtRes2;
    public javax.swing.JTextField TxtRes3;
    public javax.swing.JTextField TxtRes4;
    public javax.swing.JTextField TxtResultado;
    public javax.swing.JTextField TxtZ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
