/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.sources.vistas;

import com.umg.sources.controlador.ControladorMetodoSimplex;


/**
 *
 * @author keyor
 */
public class VistaMetodoSimplex extends javax.swing.JPanel {
    
    public VistaMetodoSimplex() {
        initComponents();
        ControladorMetodoSimplex controlador = new ControladorMetodoSimplex(new com.umg.sources.modelo.ModeloMetodoSimplex(this));
        setControlador(controlador);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelTabla = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtZ = new javax.swing.JTextField();
        CmbOpciones = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        TxtResultado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtRestriccion1 = new javax.swing.JTextField();
        TxtRestriccion3 = new javax.swing.JTextField();
        TxtRestriccion2 = new javax.swing.JTextField();
        TxtRestriccion4 = new javax.swing.JTextField();
        TxtRestriccion5 = new javax.swing.JTextField();
        BtnGenerar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BtnLimpiar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        BtnMenu = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        contenedor.setBackground(new java.awt.Color(0, 0, 102));
        contenedor.setMinimumSize(new java.awt.Dimension(1200, 800));
        contenedor.setPreferredSize(new java.awt.Dimension(1200, 800));
        contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Metodo Simplex");
        contenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        javax.swing.GroupLayout PanelTablaLayout = new javax.swing.GroupLayout(PanelTabla);
        PanelTabla.setLayout(PanelTablaLayout);
        PanelTablaLayout.setHorizontalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelTablaLayout.setVerticalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        contenedor.add(PanelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 640, 360));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Z");
        contenedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));

        TxtZ.setBackground(new java.awt.Color(0, 0, 102));
        TxtZ.setForeground(new java.awt.Color(255, 255, 255));
        TxtZ.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        contenedor.add(TxtZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 260, 40));

        CmbOpciones.setBackground(new java.awt.Color(0, 0, 102));
        CmbOpciones.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CmbOpciones.setForeground(new java.awt.Color(255, 255, 255));
        CmbOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minimizacion", "Maximizacion" }));
        CmbOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbOpcionesActionPerformed(evt);
            }
        });
        contenedor.add(CmbOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Resultado");
        contenedor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, -1));

        TxtResultado.setBackground(new java.awt.Color(0, 0, 102));
        TxtResultado.setForeground(new java.awt.Color(255, 255, 255));
        TxtResultado.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        contenedor.add(TxtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 320, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Restricciones");
        contenedor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 20));

        TxtRestriccion1.setBackground(new java.awt.Color(0, 0, 102));
        TxtRestriccion1.setForeground(new java.awt.Color(255, 255, 255));
        TxtRestriccion1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        TxtRestriccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRestriccion1ActionPerformed(evt);
            }
        });
        contenedor.add(TxtRestriccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 227, 140, 30));

        TxtRestriccion3.setBackground(new java.awt.Color(0, 0, 102));
        TxtRestriccion3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TxtRestriccion3.setForeground(new java.awt.Color(255, 255, 255));
        TxtRestriccion3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        TxtRestriccion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRestriccion3ActionPerformed(evt);
            }
        });
        contenedor.add(TxtRestriccion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 140, 30));

        TxtRestriccion2.setBackground(new java.awt.Color(0, 0, 102));
        TxtRestriccion2.setForeground(new java.awt.Color(255, 255, 255));
        TxtRestriccion2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        TxtRestriccion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRestriccion2ActionPerformed(evt);
            }
        });
        contenedor.add(TxtRestriccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 140, 30));

        TxtRestriccion4.setBackground(new java.awt.Color(0, 0, 102));
        TxtRestriccion4.setForeground(new java.awt.Color(255, 255, 255));
        TxtRestriccion4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        contenedor.add(TxtRestriccion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 140, 30));

        TxtRestriccion5.setBackground(new java.awt.Color(0, 0, 102));
        TxtRestriccion5.setForeground(new java.awt.Color(255, 255, 255));
        TxtRestriccion5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        contenedor.add(TxtRestriccion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 337, 140, 30));

        BtnGenerar.setBackground(new java.awt.Color(102, 102, 102));
        BtnGenerar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnGenerar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Generar");
        BtnGenerar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 6, -1, -1));

        contenedor.add(BtnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 190, 110, 30));

        BtnLimpiar.setBackground(new java.awt.Color(102, 102, 102));
        BtnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnLimpiar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Limpiar");
        BtnLimpiar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 6, -1, -1));

        contenedor.add(BtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, 110, 30));

        BtnMenu.setBackground(new java.awt.Color(102, 102, 102));
        BtnMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Menu");
        BtnMenu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 6, -1, -1));

        contenedor.add(BtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setControlador(ControladorMetodoSimplex c){
        BtnGenerar.addMouseListener(c);
        BtnLimpiar.addMouseListener(c);
        BtnMenu.addMouseListener(c);
        CmbOpciones.addActionListener(c);
    }

    private void TxtRestriccion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRestriccion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRestriccion3ActionPerformed

    private void TxtRestriccion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRestriccion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRestriccion2ActionPerformed

    private void CmbOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbOpcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbOpcionesActionPerformed

    private void TxtRestriccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRestriccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRestriccion1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel BtnGenerar;
    public javax.swing.JPanel BtnLimpiar;
    public javax.swing.JPanel BtnMenu;
    public javax.swing.JComboBox<String> CmbOpciones;
    public javax.swing.JPanel PanelTabla;
    public javax.swing.JTextField TxtRestriccion1;
    public javax.swing.JTextField TxtRestriccion2;
    public javax.swing.JTextField TxtRestriccion3;
    public javax.swing.JTextField TxtRestriccion4;
    public javax.swing.JTextField TxtRestriccion5;
    public javax.swing.JTextField TxtResultado;
    public javax.swing.JTextField TxtZ;
    public javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
