/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.sources.vistas;

/**
 *
 * @author keyor
 */
public class VistaPruebaMetodosTransporte extends javax.swing.JPanel {

    /**
     * Creates new form VistaPruebaMetodosTransporte
     */
    public VistaPruebaMetodosTransporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTabla = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtDatos = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        TxtRespuesta = new javax.swing.JTextField();
        BtnGenerar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TxtLimpiar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BtnMenu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1100, 800));
        setPreferredSize(new java.awt.Dimension(1100, 800));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Metodos de Transporte");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 42, -1, -1));

        javax.swing.GroupLayout JTablaLayout = new javax.swing.GroupLayout(JTabla);
        JTabla.setLayout(JTablaLayout);
        JTablaLayout.setHorizontalGroup(
            JTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        JTablaLayout.setVerticalGroup(
            JTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        jPanel1.add(JTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 680, 410));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese sus Datos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        TxtDatos.setBackground(new java.awt.Color(0, 0, 102));
        TxtDatos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TxtDatos.setForeground(new java.awt.Color(255, 255, 255));
        TxtDatos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(TxtDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 300, 30));

        jComboBox1.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Costo Minimo", "Esquina Noroeste", "Voguel" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Respuesta");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, -1, -1));

        TxtRespuesta.setBackground(new java.awt.Color(0, 0, 102));
        TxtRespuesta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TxtRespuesta.setForeground(new java.awt.Color(255, 255, 255));
        TxtRespuesta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(TxtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 250, 40));

        BtnGenerar.setBackground(new java.awt.Color(102, 102, 102));
        BtnGenerar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnGenerar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Generar");
        BtnGenerar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel1.add(BtnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, 150, 50));

        TxtLimpiar.setBackground(new java.awt.Color(102, 102, 102));
        TxtLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TxtLimpiar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Limpiar");
        TxtLimpiar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 17, -1, -1));

        jPanel1.add(TxtLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 320, 150, 50));

        BtnMenu.setBackground(new java.awt.Color(102, 102, 102));
        BtnMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BtnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Menú");
        BtnMenu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 17, -1, -1));

        jPanel1.add(BtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel BtnGenerar;
    public javax.swing.JPanel BtnMenu;
    public javax.swing.JPanel JTabla;
    public javax.swing.JTextField TxtDatos;
    public javax.swing.JPanel TxtLimpiar;
    public javax.swing.JTextField TxtRespuesta;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
