/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.sources.vistas;
import com.umg.sources.modelo.ModeloMetodosTransporte;
import com.umg.sources.controlador.ControladorMetodosTransporte;
/**
 *
 * @author keyor
 */
public class VistaMetodosTransporte extends javax.swing.JPanel {

    /**
     * Creates new form VistaMetodosTransporte
     */
    public VistaMetodosTransporte() {
        initComponents();
        ModeloMetodosTransporte modelo = new ModeloMetodosTransporte(this);
        ControladorMetodosTransporte controlador = new ControladorMetodosTransporte(modelo);
        setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void setControlador(ControladorMetodosTransporte controlador){
        BtnGenTabla.addMouseListener(controlador);
        BtnGenerar.addMouseListener(controlador);
        BtnLimpiar.addMouseListener(controlador);
        BtnRegresar.addMouseListener(controlador);
        CBBMetodos.addActionListener(controlador);  
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JLabel();
        TxtFilas = new javax.swing.JTextField();
        TxtColumnas = new javax.swing.JTextField();
        CBBMetodos = new javax.swing.JComboBox<>();
        BtnGenTabla = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BtnLimpiar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BtnRegresar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        BtnGenerar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1000, 800));
        setPreferredSize(new java.awt.Dimension(1000, 800));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Metodos de Transporte");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 42, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese Numero de Filas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        txtResultado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(255, 255, 255));
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtResultado.setText("Resultado:");
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 520, -1));

        TxtFilas.setBackground(new java.awt.Color(0, 0, 102));
        TxtFilas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TxtFilas.setForeground(new java.awt.Color(255, 255, 255));
        TxtFilas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(TxtFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 160, 40));

        TxtColumnas.setBackground(new java.awt.Color(0, 0, 102));
        TxtColumnas.setForeground(new java.awt.Color(255, 255, 255));
        TxtColumnas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        TxtColumnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtColumnasActionPerformed(evt);
            }
        });
        jPanel1.add(TxtColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 160, 40));

        CBBMetodos.setBackground(new java.awt.Color(0, 0, 102));
        CBBMetodos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CBBMetodos.setForeground(new java.awt.Color(255, 255, 255));
        CBBMetodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Costo Minimo", "Esquina Noroeste", "Vogel" }));
        jPanel1.add(CBBMetodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 180, 30));

        BtnGenTabla.setBackground(new java.awt.Color(102, 102, 102));
        BtnGenTabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnGenTabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Generar Tabla");
        BtnGenTabla.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(BtnGenTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 140, 40));

        BtnLimpiar.setBackground(new java.awt.Color(102, 102, 102));
        BtnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnLimpiar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Limpiar");
        BtnLimpiar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 8, -1, -1));

        jPanel1.add(BtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, 140, 40));

        BtnRegresar.setBackground(new java.awt.Color(102, 102, 102));
        BtnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnRegresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Regresar");
        BtnRegresar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 8, -1, -1));

        jPanel1.add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 140, 40));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        javax.swing.GroupLayout PanelTablaLayout = new javax.swing.GroupLayout(PanelTabla);
        PanelTabla.setLayout(PanelTablaLayout);
        PanelTablaLayout.setHorizontalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        PanelTablaLayout.setVerticalGroup(
            PanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        jPanel1.add(PanelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 630, 390));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ingrese Numero de Columnas");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        BtnGenerar.setBackground(new java.awt.Color(102, 102, 102));
        BtnGenerar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnGenerar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Calcular");
        BtnGenerar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel1.add(BtnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 140, 40));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ingrese los datos a la tabla");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1310, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtColumnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtColumnasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtColumnasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel BtnGenTabla;
    public javax.swing.JPanel BtnGenerar;
    public javax.swing.JPanel BtnLimpiar;
    public javax.swing.JPanel BtnRegresar;
    public javax.swing.JComboBox<String> CBBMetodos;
    public javax.swing.JPanel PanelTabla;
    public javax.swing.JTextField TxtColumnas;
    public javax.swing.JTextField TxtFilas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblDatos;
    public javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
