/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.umg.sources.vistas;

import javax.swing.JPanel;

/**
 *
 * @author keyor
 */
public class VistaMenu extends javax.swing.JPanel {

    /**
     * Creates new form VistaMenu
     */
    public VistaMenu() {
        initComponents();
    }
    
    public JPanel getBtnMetGrafico(){
        return BtnMetGrafico;
    }
    
    public JPanel getBtnMetSimplex(){
        return BtnMetSimplex;
    }
    
    public JPanel getBtnMetTransportes(){
        return BtnMetTransportes;
    }
    
    public JPanel getBtnModAsig(){
        return BtnModAsig;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnMetTransportes1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnMetGrafico = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnMetSimplex = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BtnModAsig = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BtnMetTransportes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        BtnMetTransportes1.setBackground(new java.awt.Color(102, 102, 102));
        BtnMetTransportes1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnMetTransportes1.setPreferredSize(new java.awt.Dimension(140, 45));
        BtnMetTransportes1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Metodos de transporte");
        BtnMetTransportes1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        contenedor.setBackground(new java.awt.Color(0, 0, 102));
        contenedor.setMinimumSize(new java.awt.Dimension(1200, 800));
        contenedor.setPreferredSize(new java.awt.Dimension(1200, 800));
        contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Investigacion de Operaciones");
        contenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        BtnMetGrafico.setBackground(new java.awt.Color(102, 102, 102));
        BtnMetGrafico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnMetGrafico.setMinimumSize(new java.awt.Dimension(140, 30));
        BtnMetGrafico.setPreferredSize(new java.awt.Dimension(140, 45));
        BtnMetGrafico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Metodo Grafico");
        BtnMetGrafico.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 16));

        contenedor.add(BtnMetGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 220, 90));

        BtnMetSimplex.setBackground(new java.awt.Color(102, 102, 102));
        BtnMetSimplex.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnMetSimplex.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(102, 204, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Metodo Simplex");
        BtnMetSimplex.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        contenedor.add(BtnMetSimplex, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 220, 90));

        BtnModAsig.setBackground(new java.awt.Color(102, 102, 102));
        BtnModAsig.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnModAsig.setPreferredSize(new java.awt.Dimension(140, 45));
        BtnModAsig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Modelo Asignacion");
        BtnModAsig.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        contenedor.add(BtnModAsig, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 220, 90));

        BtnMetTransportes.setBackground(new java.awt.Color(102, 102, 102));
        BtnMetTransportes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnMetTransportes.setPreferredSize(new java.awt.Dimension(140, 45));
        BtnMetTransportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Metodos de transporte");
        BtnMetTransportes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        contenedor.add(BtnMetTransportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 220, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel BtnMetGrafico;
    public javax.swing.JPanel BtnMetSimplex;
    public javax.swing.JPanel BtnMetTransportes;
    public javax.swing.JPanel BtnMetTransportes1;
    public javax.swing.JPanel BtnModAsig;
    public javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
